// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV883QddAOTMyzL99TuPWB0dqHhQpWCLM',
    appId: '1:551735925998:web:3607ca64fa2818aeafa7ff',
    messagingSenderId: '551735925998',
    projectId: 'chatty-flutter-681ec',
    authDomain: 'chatty-flutter-681ec.firebaseapp.com',
    storageBucket: 'chatty-flutter-681ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQNoGKhEsFhSGzBfiFOt67rR8VGcNRkfk',
    appId: '1:551735925998:android:3898ac5a252eff85afa7ff',
    messagingSenderId: '551735925998',
    projectId: 'chatty-flutter-681ec',
    storageBucket: 'chatty-flutter-681ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-7bfyoAsgBhg1rkYqggdreNoojROs6P0',
    appId: '1:551735925998:ios:59949e5d41360892afa7ff',
    messagingSenderId: '551735925998',
    projectId: 'chatty-flutter-681ec',
    storageBucket: 'chatty-flutter-681ec.appspot.com',
    iosClientId: '551735925998-l593d9jupk3upmf3nivl3ob8h49tgi84.apps.googleusercontent.com',
    iosBundleId: 'com.kenstarry.chattyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-7bfyoAsgBhg1rkYqggdreNoojROs6P0',
    appId: '1:551735925998:ios:414957ca3aad8643afa7ff',
    messagingSenderId: '551735925998',
    projectId: 'chatty-flutter-681ec',
    storageBucket: 'chatty-flutter-681ec.appspot.com',
    iosClientId: '551735925998-bnns6e29ftusg4t6vepkv4tndjbu7gbk.apps.googleusercontent.com',
    iosBundleId: 'com.kenstarry.chattyFlutter.RunnerTests',
  );
}
